Fix: [Savegames] dynamically adjust antenna radius to fit old reaches
TVTower/TVTower pull request #1133
Opened 2024-04-21 09:22 UTC by GWRon

Closes #1127

2024-04-21 11:04 UTC, nittka requested changes

2024-04-21 11:32 UTC, GWRon commented on source/main.bmx
> +						Local newRadius:Int = 31 'calculated in earlier versions
Jo ... aber das kuemmert mich an sich relativ "wenig". Wir koennen es nicht allen recht machen - und solange Dir nicht innerhalb weniger Minuten eine praktikable und alles erschlagende Methode einfaellt, sollte man bei einer solchen (nun existierenden) Loesung bleiben.

Alles andere sorgt nur fuer Unmut bei uns (Entwicklungszeit) und trotzdem noch Unmut bei 2-3 Spielern die unbedingt ihr altes Spiel in einer neuen Version weiterspielen wollen, aber irgendwo eine Abweichung vorhanden ist.

2024-04-21 11:35 UTC, GWRon commented on source/main.bmx
> +						Local newRadius:Int = 31 'calculated in earlier versions
Falls Du meinst, dass der Radius neuer Antennen mindestens einen beim Einladen "korrigierten Radius" erhaelt:
- welchen denn?
- was ist mit Spielern die in der alten Version sich haetten einen neuen Sendemast kaufen koennen, nun aber dank vergroessertem "Standardradius" mit 50% Mehrkosten konfrontiert werden?

Wir haben einen Radius der sich in neuen Spielen am Startjahr orientiert, bei alten Spielen wird der Bestand angepasst um den "Status Quo" beizubehalten. Aber alles ab "Einladen" wird Abweichungen beinhalten (Preise, Reichweiten neuer Antennen, ...).

2024-04-21 11:38 UTC, nittka commented on source/main.bmx
> +						Local newRadius:Int = 31 'calculated in earlier versions
Das meinte ich ja mit max(radiusAlt + x, 45). Damit bekommt man zumindest abgedeckt, dass bei einem größeren Startradius auch der neue nicht zu klein ist.

2024-04-21 11:42 UTC, GWRon commented on source/main.bmx
> +						Local newRadius:Int = 31 'calculated in earlier versions
Ich verstehe das gerade nicht. Woher kommt denn "+x" - aus der For-Loop?

Klar kann man das "deckeln", aber dann hast du eventuell nach dem Einladen weniger Reichweite als im Vorversionsspiel.

2024-04-21 12:08 UTC, nittka commented on source/main.bmx
> +						Local newRadius:Int = 31 'calculated in earlier versions
Damit wir uns nicht missverstehen. An der Berechnung der Radien für die Bestandsantennen habe ich nichts auszusetzen. Mir geht es ausschließlich um den "Map-Radius" (antennaStationRadius) für neu zu bauende Antennen. Der sollte sich aufgrund der neuen Logik für ein geladenes Spiel typischerweise auch erhöhen. (Geladenes Spiel 1985 Radius 20, neues Spiel 1985 Radius 

Wenn man ein neues Spiel startet, wird der berechnet und ist gedeckelt (falls die Mindestreichweite nicht erreicht wird und ein Kabelvertrag abgeschlossen wird). Für ein geladenes Spiel sollte ein angepasster Radius also auch nicht "beliebig groß" werden können.

Das x ist nun ein noch festzulegender, konstanter Wert (z.B. 10).

2024-04-21 12:41 UTC, nittka commented
Vorschlag eingebaut.

2024-04-21 14:11 UTC, GWRon commented
v0.82 - 1985 gestartet, 3 Sendemasten (also Speicherstand von den Screenshots oben)
Kauf eines neuen Mastes:
![image](https://github.com/TVTower/TVTower/assets/2625226/52e90ec2-cbae-4e47-ab67-5092f62fa9d3)

v0.83dev Speicherstand eingeladen
Kauf eines neuen Mastes:
![image](https://github.com/TVTower/TVTower/assets/2625226/ad62d06d-7c57-47c6-9189-70a1a73a1b33)

Ohne Deine Aenderung ist natuerlich der Sendemastradius viel zu klein (da noch keine Radius-Umrechnung erfolgt). Deine Aenderung hat aber denke ich bei "fruehen Spieljahren" noch zu viel Einfluss. Dein "max(..)" sorgt ja MINDESTENS fuer 45er Radien.

2024-04-21 14:31 UTC, GWRon commented
Also man muesste den Antennenradius erstmal nach "Databased" umwandeln:
```
			'convert default radius to new data-related value
			Local newAntennaRadius:Int = mapInfo.ScreenToData(GetStationMapCollection().antennaStationRadius)
			GetStationMapCollection().antennaStationRadius = min(newAntennaRadius + 10, 45)
```

Aber ich habe nun das ganze so umgesetzt, dass es als Faktor die "Share-Aenderung" zwischen unserem Basiswert (von 1985) einbezieht.
Wenn also von 50 auf 25% sinkt, kommt ein Faktor von 2.0 zum tragen (bzw radius/0.5). Das ganze wird dann noch auf "45" gedeckelt.

2024-04-26 14:25 UTC, nittka approved these changes

2024-04-26 14:30 UTC, merged