[Misc] Script expressions: Support ".role" and "self:role"
TVTower/TVTower pull request #1198
Opened 2024-10-22 18:32 UTC by GWRon

Allow 
Programme: ${.self:"role":castIndex:"fullname"}
Programme: ${.self:"cast":castIndex:"roleid"}
generell: ${.role:roleGUID/roleID:"fullname"}

2024-10-22 18:35 UTC, GWRon commented
Ja ich weiss, es enthaelt doppelten Code.
```
		self.role_id: ${.self:"cast":1:"roleid"}, 
		self.role: ${.self:"role":1:"fullname"}, 
		role: ${.role:"a00ea58a-4a9f-466e-9fe5-cf8b53730b60":"fullname"}, 
		role_indirekt: ${.role: ${.self:"cast":1:"roleid"}:"fullname"}
```
basierend auf:
```
			<staff>
				<member index="0" function="1">2b6fb1b7-57b7-44bf-b930-a032d9193475</member>
				<member index="1" function="2" role_guid="a00ea58a-4a9f-466e-9fe5-cf8b53730b60">dc2348e7-382c-4fad-98b6-bd0df974d274</member>
				<member index="2" function="2">6cb07810-f86a-4dd4-bf9a-3b2afb574826</member>
				<member index="3" function="2">32c2f4c6-e8a6-40c3-8659-c0bf6cd37854</member>
			</staff>
```
ergibt:
```
self.role_id: 16845, self.role: Snow White, role: Snow White, role_indirekt: Snow White
```

Man koennte alles ueber das "indirekte" Zugreifen erreichen, sobald man sich die ID geholt hat ... ich vermute aber, dass es so ein wenig "lesbarer" im Code bleibt.

2024-10-23 15:07 UTC, nittka commented
Ich hatte überlegt ob es Mehrdeutigkeitsprobleme geben könnte (gleicher Schauspieler bei mehreren Cast-Indizes verwendet), aber so lange man über den Index referenziert, sollte es funktionieren. Nur wenn man über die person-ID die Rolle in einer Lizenz ermittlen wollen würde, gäbe es wohl Ärger.

2024-10-23 15:18 UTC, nittka requested changes
Kleinigkeiten... (ansonsten wäre ich weiterhin dafür, die häufig zu erwartenden properties in den cases nach oben zu schieben)

2024-10-23 15:18 UTC, nittka commented on source/game.gamescriptexpression.bmx
> +'${.programmedata:"title"} - context: TProgrammeData
copy/paste-Fehler - .role, context Rolle

2024-10-23 15:18 UTC, nittka commented on source/game.gamescriptexpression.bmx
> +		case "countrycode"  Return New SToken( TK_TEXT, role.countrycode, params.GetToken(0) )
der Vollständigkeit title noch ergänzen?

2024-10-23 16:31 UTC, scr0llbaer9000 commented on source/game.gamescriptexpression.bmx
> +		case "countrycode"  Return New SToken( TK_TEXT, role.countrycode, params.GetToken(0) )
nickname bitte auch unterstüzen, wenn wir schon dabei sind.

ist bei rollen fast noch viel geläufiger.

2024-10-23 16:50 UTC, GWRon commented on source/game.gamescriptexpression.bmx
> +		case "countrycode"  Return New SToken( TK_TEXT, role.countrycode, params.GetToken(0) )
> nickname bitte auch unterstüzen, wenn wir schon dabei sind.
> 
> ist bei rollen fast noch viel geläufiger.

```
        'name of the character 
        Field firstName:string
        Field lastName:string
        'title - like "Dr." or "Prof."
        Field title:string 
        Field gender:int
        Field countryCode:string = ""
        'is this a custom role not used in a real world movie
        Field fictional:int = False
```

Gibt nicknames gibt es bisher noch nicht..also war bisher nicht im Objekt vorgesehen.

2024-10-24 13:28 UTC, nittka commented on source/game.gamescriptexpression.bmx
> +		case "countrycode"  Return New SToken( TK_TEXT, role.countrycode, params.GetToken(0) )
(und Titel gibt es bei Personen noch nicht, da sind diese beiden Objekte wohl irgendwann mal auseinandergelaufen)

2024-10-24 19:59 UTC, GWRon commented on source/game.gamescriptexpression.bmx
> +		case "countrycode"  Return New SToken( TK_TEXT, role.countrycode, params.GetToken(0) )
#1199 wuerde dies bereitstellen.

2024-10-24 20:31 UTC, GWRon commented
> Kleinigkeiten... (ansonsten wäre ich weiterhin dafür, die häufig zu erwartenden properties in den cases nach oben zu schieben)

Das kannst Du dann gerne in einem separaten PR angehen.

2024-10-25 04:00 UTC, nittka approved these changes
OK, falls Titel etc. dazukommen, gern hier noch ergänzen.

2024-10-29 09:22 UTC, merged