Expression-Support erweitern
TVTower/TVTower pull request #1236
Opened 2024-11-24 15:01 UTC by nittka

2024-11-24 15:16 UTC, GWRon commented
Damit bringst Du aber nun eine parentScript-Referenz ins Spiel (nicht nur die ID), die zwar nicht im Speicherstand persistiert wird, aber doch waehrend der "Session" die Referenz beibehaelt.

Sollte zwar kein Problem sein, aber wenn es vermeidbar waere ... vlt braucht es da ja auch nur, wenn ":parent" im Titel/Description vorkommt ?

2024-11-24 15:19 UTC, nittka commented
Andere Variante wäre, sie sofort nach der Titelerzeugung wieder zu entfernen. Werden immer gleich alle Sprachen "aufgelöst" oder nur bei Bedarf?

2024-11-24 15:34 UTC, GWRon commented
Aufgeloest werden alle in einem Rutsch.

Vlt ist ein "extra" container besser (falls man sonst mehrere temporaere Daten dem Objekt hinzufuegen wuerde).


Die Alternative waere wohl, die Templates usw. schon zeitnah der Collection hinzuzufuegen (Achtung titleprotection).

Oder bei der Collection tempListen (AddTemporary...) hinzuzufuegen und die dann pruefen. Waere also eine Zentralisierung der temporaeren Daten.

2024-11-24 15:39 UTC, nittka commented
Refactoring für später? Aktuell benötigen wir ja nichts außer dem parent.

2024-11-24 15:51 UTC, GWRon commented
Ja das kann später gemacht werden.

Bin mir aber bei dem "localizedString.toString()"-"${" check nicht ganz sicher. Also sich drauf zu verlassen, dass das Format so bleibt.

Vielleicht eine Funktion schreiben, die durch alle Entries geht und sofort return macht, sobald in einem der Eintraege das Gesuchte vorkommt. Ist expliziter, als sich auf ToString zu verlassen.

2024-11-24 19:26 UTC, GWRon commented
Can you rename "ContainsExpression" to something like "ContainsString" ? 
This way TLocalizedString does not need to know about expressions ...

2024-11-25 08:21 UTC, nittka commented on source/Dig/base.util.localization.bmx
>  			If langIndex >= 0 and valueStrings[langIndex] And valueStrings[langIndex].contains("${") Then Return True
upsi

2024-11-25 09:13 UTC, GWRon requested changes

2024-11-25 09:13 UTC, GWRon commented on source/game.gamescriptexpression.bmx
> +		If Not licence Then Return New SToken( TK_ERROR, ".self has no parent", params.GetToken(0) )
```
		If licence.parentLicenceGUID
			licence = licence.GetParentLicence()
		Else
			Return New SToken( TK_ERROR, ".self has no parent", params.GetToken(0) )
		EndIf
		If Not licence Then Return New SToken( TK_ERROR, ".self has no parent", params.GetToken(0) )
```

Wenn licence vorher "null" ist, dann braucht hier ja nicht unterscheiden ...
```
		If licence.parentLicenceGUID Then licence = licence.GetParentLicence()
		If Not licence Then Return New SToken( TK_ERROR, ".self has no parent", params.GetToken(0) )
```
wuerde dann ja ausreichen.

2024-11-25 09:14 UTC, GWRon commented
Abgesehen von der kleinen Optimierung (die Du auch ablehnen kannst -- bspweise weil Du in der TK_ERROR-Meldung unterscheiden willst zwischen "keine guid definiert" und "kein Eintrag zur GUID gefunden"), kannst Du gerne mergen.

2024-11-25 09:17 UTC, GWRon commented on source/game.gamescriptexpression.bmx
> +		If Not script Then Return New SToken( TK_ERROR, ".self has no parent", params.GetToken(0) )
Auch hier koennte wohl "gekürzt" gecheckt werden ... da bei "parent" IMMER auf _parentScriptTmp gecheckt werden sollte - und falls das _parentScriptTmp nicht existiert, sollte es bei `propertyName = "parent"`-Fällen ja immer "erroren" - oder nicht?

2024-11-25 09:41 UTC, nittka commented on source/game.gamescriptexpression.bmx
> +		If Not script Then Return New SToken( TK_ERROR, ".self has no parent", params.GetToken(0) )
hier sollte die Abkürzung funktionieren.

2024-11-25 10:51 UTC, GWRon commented on source/game.gamescriptexpression.bmx
> +		If Not licence Then Return New SToken( TK_ERROR, ".self has no parent", params.GetToken(0) )
Stimmt ... da muesste man vorher die ID sichern und dann schauen, ob es eine "andere" ist.
Denke da ist der Code hier schon ausreichend genug. My fault :)

2024-11-25 10:52 UTC, GWRon commented
OK, aber nun denke ich - bereit fuer Merge :)

2024-11-25 11:03 UTC, merged