Final Polish translations
TVTower/TVTower pull request #1253
Opened 2024-12-10 19:12 UTC by pauldim

Final Polish translations. This PR is co-created with scr0llbaer9000. We can do the rest of the shortcomings later.

2024-12-10 21:01 UTC, scr0llbaer9000 commented
Did not come around for a final round of checks / fixes:

- All references to roles in `eggi_screenplays_adaptations.xml` must be fixed (wrong quotation marks messed up by translation tool) (had noticed that, but forgot).

- `database_programmes.xml` has a `[2|Nicka]a` that must be fixed to `${.self:"cast":2:"nickname"}a` (validator kinda finds that by coincidence)

- variable options count mismatches with the other languages in `database_scripts.xml` in lines 394, 939, 970, 980, 1021

- variable options count mismatch in `scr0llbaer_news.xml in lines` 1336 f (forgot some `|` characters at the end)

- variable options count mismatch in `scr0llbaer_screenplays_adaptations.xml` in lines 6292, 7356, 7694, 9517

- property name got errouneously tanslated in `scr0llbaer_screenplays_adaptations.xml` line 1694 (must be `"firstname"` instead of `"imię"`)

That's all I have for now.

btw validator doesn't update in my eclipse @nittka , is that problem on your side? So it's still a bit hard to wade through everything.

2024-12-11 05:55 UTC, nittka commented
I will review the changes and give additional feedback. After the merge, my suggetion would be for pauldim to create a backup-branch of his current master (if wanted) and do a hard-reset + force-push on the official master (cannot be done in the browser, but must be done from a client). In the standard case, the fork's master should be kept in synch by pulling/fast forward merges rather than merge commits. Contributions/on changes should be done on a branch and not the master.

@scr0llbaer9000 : There are still some PRs open that have impact on the editor. I wanted to know if they are merged or rejected before I release a new editor version.

2024-12-11 07:26 UTC, nittka requested changes
I still have to go through the changes in the main programmes file (old cast reference in line 84566 [2|Nick...).
Please fix the formal issues first. Only after that is done, it makes sense to run the test script that tries to find unresolvable references/variables.

2024-12-11 07:26 UTC, nittka commented on res/database/Default/user/scr0llbaer_screenplays_adaptations.xml
> +				<pl>${.self:"role":1:"imię"}</pl>
parameter firstname - not translated

2024-12-11 07:26 UTC, nittka commented on res/database/Default/user/scr0llbaer_screenplays_adaptations.xml
> +					<pl>Martwy|Opuszczony|Zimny|Ponury|Mroczny</pl>
5 alternatives here, 6 in the other languages

2024-12-11 07:26 UTC, nittka commented on res/database/Default/user/scr0llbaer_screenplays_adaptations.xml
> +					<pl>Szalona|Wściekła|Oszalała|Rozgorączkowana|Obłąkana|Śmieszna|Maniacka|Maniakalna|Absurdalna|Groteskowa|Dziwaczna|Odlotowa</pl>
12 alternatives here, 13 in the other languages

2024-12-11 07:26 UTC, nittka commented on res/database/Default/user/scr0llbaer_screenplays_adaptations.xml
> +					<pl>Tajemnica|Zagadka|Mit|Sekret</pl>
4 alternatives here, 5 in the other languages

2024-12-11 07:26 UTC, nittka commented on res/database/Default/user/scr0llbaer_screenplays_adaptations.xml
> +					<pl>Keen Billy Blaze|${space} ${adventures} ${captain} Keena Billego Blaze'a|${galactic} ${adventures_c} ${captain} Keena Billego Blaze'a</pl>
no role references here?

2024-12-11 07:26 UTC, nittka commented on res/database/Default/user/scr0llbaer_screenplays_adaptations.xml
> +					<pl>Nowe|Nowe|Dalsze|Świeże|Bezprecedensowe|Kolejne|Niewypróbowane|Nieskazitelne|Odświeżone|Ożywione|Odnowione|Odrodzone|Ożywione|Ożywione</pl>
14 alternatives here, 15 in the other languages

2024-12-11 07:42 UTC, nittka commented
In programmes.xml very many original titles for French/Italien etc. have been removed. (I compared the files from master and this PR with all Polish tags removed - ideally they should be largely identical).

2024-12-11 10:14 UTC, pauldim commented on res/database/Default/user/eggi_screenplays_adaptations.xml
> +				<pl>${.self: „role”:1: „firstname”} i ${.self: „role”:2: „firstname”}, niedopasowana para z chicagowskiej sceny artystycznej, zmaga się z problemami małżeńskimi. Pomiędzy seminariami i marzeniami
Done

2024-12-11 10:26 UTC, pauldim commented on res/database/Default/database_news.xml
> +						${age} letnia uczenica;ona;jej;${.persongenerator:"fullname":"pl":"female";Złamała}
Corrected

2024-12-11 10:35 UTC, pauldim commented on res/database/Default/database_news.xml
> +				<pl>Po szumie po Mistrzostwach Świata, gra „Wyzwania w ${armwrestling_${i}}“ autorstwa ${artistlastlastname}soft znajduje się obecnie na szczycie międzynarodowych list sprzedaży.</pl>
There is so much to look at and so many mistakes. Corrected.

2024-12-11 10:39 UTC, pauldim commented on res/database/Default/database_scripts.xml
> +							<pl>są tam, żeby narzekać, bo nie zgadzają się z traktowaniem swoich dziadków. ${.ufirst:who} pośredniczą bez przemocy.</pl>
Done

2024-12-11 12:46 UTC, pauldim commented on res/database/Default/user/scr0llbaer_screenplays_adaptations.xml
> +					<pl>Keen Billy Blaze|${space} ${adventures} ${captain} Keena Billego Blaze'a|${galactic} ${adventures_c} ${captain} Keena Billego Blaze'a</pl>
Grammar difficulties :)

2024-12-11 12:46 UTC, pauldim commented on res/database/Default/user/ariksan.xml
> +				<de>${title} in ${randomcity}</de>
<pl>${title} w ${randomcity}</pl> - There must be a Polish version

2024-12-11 12:48 UTC, pauldim commented on res/database/Default/database_ads.xml
> +				<all>${brand_bestbuy}</all>
Media Markt in Poland. Great , that we have this functionality of original ads. I just noticed it.

2024-12-11 13:02 UTC, nittka requested changes
In case you are interested where Polish translations (title) are still missing (probably last minute additions in one of the recent commits):
* scr0llbaer.xml line 1271 and following: d26ee4f9-1b61-4b7a-926a-e462256b127b and episodes
* scr0llbaer.xml line 1354: d664f243-15d6-4645-886e-27a3e8cf8533
* database_ads.xml line: 360b9ee1-9e2e-469d-b61e-fa8a69cbf560 (set brand explicitly)
* database_programmes.xml line 7622: 216d7e50-2893-4a2e-973a-4f55a3ab81b0
* database_programmes.xml line 53814: 6543de67-43ce-4a32-ab3f-c7c1dbbae34a

2024-12-11 13:03 UTC, pauldim commented on res/database/Default/user/ariksan.xml
> +					<!-- In PL  <adjective_m> or <adjective_w> -->
Like this:
<adjective>
					<de>witzige|aufgeweckte|gescheite|kluge|lustige</de>
					<en>Witty|Sharp|Clever|Smart|Funny</en>
					<pl>Dowcipn|Ostr|Sprytn|Inteligentn|Zabawn</pl>
				</adjective>
				<adjective_m>
					<pl>${adjective}y</pl>
				</adjective_m>
				<adjective_w>
					<pl>${adjective}a</pl>
				</adjective_w>
Corrected

2024-12-11 14:36 UTC, nittka commented
I started checking with the test script...
* database_programmes line 112010: you fixed the reference, but the square brackets are still present `[` and `]` should be removed
* ariksan line 511: variable name ${animal2} was translated
* database_scripts line 1104: variable ${who_${i}} should be replaced by ${who}
* scr0llbar_news line 1362: the number of entries within the csv tvtowermeta_csv does not match. It looks like one pair of translations is missing (8 entries instead of 10). Also, are the white spaces after the semicolon intended? They will be present in the resulting text.
* database_news line 3981: again too few csv elements; I guess, the comma after Rio de Janeiro should be a semicolon. Note also that in the alternatives of this entry, there is always a white space in the second entry except for London (first alternative)

2024-12-11 14:45 UTC, nittka commented
database_news line 7000: one csv entry missing - i guess the comma after heavy metalovy should be a semicolon

2024-12-11 16:49 UTC, pauldim commented
`<scripttemplate product="1" licence_type="1" guid="443fa70e-450c-4085-a4de-c41b23e295ef" creator="9551" comment="Description largely by ChatGPT">
			<title>
				<de>Sekretärinnen-Bericht 3. Teil - Stenografie, Streiche &amp; Sinnlichkeit</de>
				<en>Secretaries Report Part 3 - Shorthand, Stunts &amp; Sensuality</en>
				<pl>Raport sekretarek, Część 3 - Skróty, akrobacje i zmysłowość</pl>
			</title>
			<description>
				<de>Jetzt wird's noch bunter: ${.self:"role":1:"fullname"} wird zur Meisterin der Stenografie und anderer Quickies, Fax und Fon klingeln im Rhythmus der Aktion und ${.self:"role":2:"fullname"}s klappernder Schreibmaschine... Inmitten biederer Bürokratie brodelt feurige Fantasie.</de>
				<en>Now it all gets extra sparkly: ${.self:"role":1:"fullname"} becomes a master of shorthand and other quickies, fax and phone ring to the rhythm of the action and ${.self:"role":2:"fullname"}'s clattering typewriter.**,,** In the midst of bland bureaucracy, fiery fantasies are fizzing.</en>`

There should be two commas in the English version?

2024-12-11 17:26 UTC, nittka commented
No, I think the two commas should be dots - as in German. typewriter... In the midst

2024-12-11 17:46 UTC, pauldim commented
I think everything has been corrected. I don't think I missed anything.

2024-12-11 22:47 UTC, scr0llbaer9000 commented
> After the merge, my suggetion would be for pauldim to create a backup-branch of his current master (if wanted) and do a hard-reset + force-push

...or just delete the TVTower fork and fork TVTower again. And then create a *branch* for your own experiments.

2024-12-12 15:54 UTC, nittka commented
Test script and editor validation look fine. I'll merge tomorrow if I don't hear any objections.

2024-12-12 17:47 UTC, scr0llbaer9000 commented
The texts for the new blockbuster achievements in [database_achievements.xml](https://github.com/TVTower/TVTower/blob/master/res/database/Default/database_achievements.xml) are still untranslated.

Only very few lines that could be done in this PR, then that will be all as far as I can see.

2024-12-13 21:18 UTC, pauldim commented
> @pauldim : please let me know, if you want to address the blockbuster achievement.

I didn't notice that comment. I've already added those translations.

2024-12-14 06:56 UTC, nittka commented
Almost there. When working on improvements on the editor validation two subtle issues came up that the current validation and the test script missed (note that this script cannot guarantee 100% coverage of all possible alternatives, so even in combination editor and test script are not guaranteed to find all issues).

@scr0llbaer9000 and @pauldim please let me know if you want to correct those issues in this PR or separately (Polish translation is affected for one of them)

* trivial issue: scr0llbaer_news line 416 (733f6d6a-4021-45c0-8ace-7768f9a922f0) - in German the last alternative ends with pipe (|), i.e. there is another unintended empty alternative; remove the pipe
* less trivial: scr0llbar_news lines 630 and following (8ac54969-a412-4c23-98c1-a3b2f449605d) - the csv data alternatives 5 (all languages) and 6 (en and pl) of the variable what_csv are not consistent with the rest. All other entries have 3 data points (2x semicolon) but 5 and 6 have only 2 data points (1x semicolon). But the third datapoint is never referenced (...what_csv:2 cannot be found), so the texts there will never be used. Note that there is no support for escaping at the moment.

2024-12-14 10:46 UTC, scr0llbaer9000 commented
> trivial issue

not so trivial? or why didn't the validator find it before?

> scr0llbar_news lines 630 and following

ah yeah, these are "real" semicolons. Was wondering there might be instances of those. Originally used them because of casing. Can change to full stops now.

I'll fix these when you merge.

2024-12-14 13:22 UTC, merged

2024-12-14 13:27 UTC, nittka commented
> or why didn't the validator find it before?

The bug simply never surfaced. If TVTower determines the used alternative based on English (no idea), the additional German one will never cause errors. If the 100 interations of the test script never chooses the last German one... With the validation working for the rest of the cases, there was no reason to check the code.

New editor version is available.