Support for inch, one-third and possibly other chars
TVTower/TVTower pull request #1256
Opened 2024-12-12 18:07 UTC by scr0llbaer9000

I don't intend to contribute to code in the future, only this little thing for now.

I compiled and tried, the inch (`″`) and the (`⅓`) are working now when they appear in the content. However, the Phi symbol and the Heart symbol is not. But maybe the problem is on my end (something with system font)?

2024-12-15 08:38 UTC, GWRon commented
I thought the UTF8-code might be incorrect for the not displayed ones... but using `print Asc("ɸ")`" prints 632 ... and also adding it directly via `:+ "ɸ"` resulted in the same "not displayed".

A simple check of "Source Sans Pro" seems to tell: this glyph is not contained in the font. If that is the case we can only render out these glyphs if we use a font containing them.

2024-12-15 09:18 UTC, nittka commented
As letters seem to be a bit wider in Noto Sans, we should be careful. Titles, descriptions, signs etc. that fit with the old font might not work any more. Should not be addressed for the current release.

2024-12-15 09:21 UTC, GWRon commented
@scr0llbaer9000 Maybe you find a "xxx sans" font which contains the glyph of your choice (the heart) ?

Regarding the font "similarity" I saw comparing the fonts:
https://old.reddit.com/r/typography/comments/480zna/what_are_differences_between_notodroid_and_open/
... they are the same (despite some glyphs here and there ... and font weight adjustments)

I thought of checking what chrome uses here to display the unicode chars... "Google Sans Flex" - did not check that for now (just checked Roboto Flex from google which does not contain the heart either.

I am with @nittka to not address this for the next release (for the same reasons)

2024-12-16 01:51 UTC, scr0llbaer9000 commented
Then this PR can be merged as is, with the TODO comments?

I'll "fix" the Phi symbol in the database. Heart wasn't used yet.

2024-12-16 08:33 UTC, nittka requested changes
I'd propose commenting out the lines that cannot work with the current font.

2024-12-17 05:17 UTC, scr0llbaer9000 commented
commented out for the time being.

2024-12-17 05:29 UTC, nittka approved these changes

2024-12-17 13:30 UTC, merged