Original Titles added and cleanup
TVTower/TVTower pull request #337
Opened 2021-04-10 10:34 UTC by jukey

original titles added for content with imdb_id
some imdb_ids added, some imdb_id duplicates resolved
cleanup and fixes of some original_titles
release year fix for 'Die Feuerzangenbowle'

This PR contains all changes done in https://github.com/TVTower/TVTower/pull/335 bit does not have an initial commit containing an unneccesary merge from TVTower -> My Fork.

2021-04-10 14:15 UTC, nittka requested changes

2021-04-10 14:15 UTC, nittka commented on res/database/Default/database_programmes.xml
> +				<de>TodMister Universum</de>
Leerzeichen vergesssen?

2021-04-10 14:15 UTC, nittka commented on res/database/Default/database_programmes.xml
> +				<de>UhrwerkOrgange</de>
Leerzeichen vergessen?

2021-04-10 14:15 UTC, nittka commented on res/database/Default/database_programmes.xml
>  			<ratings critics="89" speed="65" outcome="65" />
Bei dieser rückgängig gemachten Korrektur sollten auch die alten Ratings wieder hergestellt werden.

2021-04-10 15:35 UTC, jukey commented on res/database/Default/database_programmes.xml
> +				<de>TodMister Universum</de>
Good catch!

2021-04-10 15:36 UTC, jukey commented on res/database/Default/database_programmes.xml
> +				<de>UhrwerkOrgange</de>
Jupp :)

2021-04-10 15:38 UTC, jukey commented on res/database/Default/database_programmes.xml
>  			<ratings critics="89" speed="65" outcome="65" />
Habe die [ursprünglichen](https://github.com/TVTower/TVTower/pull/109/commits/0d7edc3ac220dbcbd0fe96769a5cc790fa9ae35d#diff-1398ca9e582fb329aeab0656d6153b8f0f64a96fd984dbf204d758d5b2f6f035L1585) Werte wiederhergestellt.

2021-04-10 16:17 UTC, nittka approved these changes

2021-04-10 16:18 UTC, nittka commented
Sieht für mich OK aus. Die finale Entscheidung würde ich aber @GWRon überlassen wollen.

2021-04-11 00:39 UTC, GWRon commented
Ihr koennt auch ohne mich den Deckel zu machen ;-).

2021-04-11 05:51 UTC, merged

2021-04-11 05:54 UTC, nittka commented
Die commits waren auf dem fork direkt auf dem master. Besser ist es den PR von einem Branch aus zu stellen, damit es bei einem Update des master-Branches vom Haupt-Repo aus nicht zu Konflikten kommt.

2021-04-11 06:24 UTC, jukey commented
Danke für den Hinweis. Ich werde in Zukunft nicht nur einen branch im fork anlegen, sondern ihn auch benutzen. ;-)