Feat chooseable amateurs
TVTower/TVTower pull request #388
Opened 2021-08-11 21:18 UTC by GWRon

- Verfuegbare Amateure in eigener Liste (damit immer die "gleichen" Leute statt immer Zufall pro "Listenaufruf")
- Liste wird aller 4 Stunden erneuert / durchgewuerfelt
- Amateure listen nun ihre Produktionen auf
- Upgrade von Amateur zu Profi/Promi nach Abschluss der dritten Produktion mit demselben Beruf (statt vorher "alle Berufe zusammen")
- Auswahllisten haben nun immer 5 Amateure mit zur Auswahl

![aufwertung](https://user-images.githubusercontent.com/2625226/129104666-7c1e4c0e-485b-4a25-becb-7b5b37e1068a.gif)

2021-08-12 10:53 UTC, nittka requested changes
Ich habe keine Hinweise zum konkreten Code. Folgende Anmerkungen nach einem ersten kurzen Testspielen (und Codeüberfliegen):
* Ich finde den Ansatz für die "Beschwerden" zur Cast-Auswahl gut.
* Ich habe ein bisschen Bauchschmerzen bei der aktuellen Filter-API. Man kann einen Country-Code mitgeben (der aktuell scheinbar aber nicht gesetzt wird). Gefühlt würde ich von den fünf Amateuren pro Geschlecht 3 aus dem eigenen Land (Spracheinstellung) und 2 zufällige Länder gut finden.
* Blocker: Das Übernehmen der Einstellungen im Supermarkt funktioniert nicht richtig (siehe unten).
* Ich hätte die Sortierfunktionen im Supermarkt gern angepasst (Name: wirklich nach Name!, Berufserfahrung, Genreerfahrung: Amateure zuletzt, Gage: wirklich nach Gage, da manche Amateure wegen Ausbildung schon teurer sind). Bei einem Amateur gehe ich mit der Sonderstellung (immer zuerst) mit. Bei fünf will ich zumindest nicht kampflos aufgeben.
* Die Regel Profi nach X Produktionen würde ich gleich in die Konfigurationsdatei einfließen lassen.

Zum Übernehmen der Einstellungen. Ich stelle für Folge 1 den Cast zusammen und schließe mit Einstellungen übernehmen ab. Für Folge 2 sind dann die Leute eingetragen und ich ändere einen Eintrag und schließe ab. Dann wird die geänderte Besetzung auch für Folge 1 angezeigt. Ob die Besetzung dann auch im Programm falsch ist, kann ich nicht sagen, denn bei mehreren Scripten (Typentausch, die NachtX, tanz-amiz) ist die Auswahl im Programmplaner nach Abschluss der Dreharbeiten leer (übrigens auch, wenn man die Einstellungen nicht geändert hat)! Hier ist grundsätzlich was kaputt gegangen.

2021-08-12 16:01 UTC, GWRon commented
> Zum Übernehmen der Einstellungen. Ich stelle für Folge 1 den Cast zusammen und schließe mit Einstellungen übernehmen ab. Für Folge 2 sind dann die Leute eingetragen und ich ändere einen Eintrag und schließe ab. Dann wird die geänderte Besetzung auch für Folge 1 angezeigt.

Ich glaube, das war auch schon vorher "kaputt". Der Fehler ist eher folgend:
- es veraendert auch die Besetzung einer "abgeschlossenen" Planung
- es ueberschreibt auch die bereits vorgenommene Besetzung (das kann ja gewuenscht sein) 

An sich fehlt da wohl nur der Check fuer "Punkt 1"


> Ob die Besetzung dann auch im Programm falsch ist, kann ich nicht sagen, denn bei mehreren Scripten (Typentausch, die NachtX, tanz-amiz) ist die Auswahl im Programmplaner nach Abschluss der Dreharbeiten leer (übrigens auch, wenn man die Einstellungen nicht geändert hat)! Hier ist grundsätzlich was kaputt gegangen.

Da muss ich erstmal nachschauen, was Du da genau meinst ("nachstellen").

2021-08-18 04:46 UTC, nittka commented
In der Beschreibung hatte ich mich vielleicht nicht genau genug ausgedrückt. Wenn man Serien produziert, sind diese nach Ende der Produktion nicht verfügbar. Es kommt zwar die Nachricht, aber im Programmplaner ist die Serie nicht sichtbar. Filme scheinen zu gehen, Shows habe ich nicht nochmal ausprobiert.

Zur Sortierung der Leute im Supermarkt (und der "Ausbildungsdauer" in der config) hast Du Dich noch nicht geäußert.

2021-08-18 12:41 UTC, GWRon commented
config: ich sagte dazu doch was - weiss nur nicht mehr wo. Und zwar, dass man ueberlegen koennte, die gesamten "GameRules" per Reflection und ner XML-Config-Datei anpassbar zu machen.


@ Serienproduktion
Kann ich nachvollziehen und schau mir das an.

2021-08-18 13:51 UTC, nittka commented
Dann scheinen es nicht alle Deine Kommentare nach Github geschafft zu haben (bitte nochmal prüfen). Wenn Du überlegst, den Config-Teil zu verallgemeinern, kann es erstmal so bleiben (separates Ticket). Für "Reflection" wäre dann nur wichtig, dass man auf leichtem/standardisierten Weg rausfinden kann, was konfigurierbar ist.

2021-08-18 13:55 UTC, GWRon commented
ja Reflection wuerde natuerlich wenig "Kommentar" mit sich bringen.

Du kannst gerne alles aus GameRules per dev.xml konfigurierbar machen, was Du fuer "noetig" haeltst (sollte nahezu nur copy-paste +adjust sein)

2021-08-18 14:03 UTC, nittka commented
Ich schreibe mir die GameRule-Konfiguration mal auf meine private TODO-Liste (aber eher mittel- als kurzfristig).

2021-08-18 22:53 UTC, GWRon commented
Serienproduktion sollte wieder zu ausstrahlbaren Episoden fuehren.

2021-08-19 17:54 UTC, nittka commented
Kurzes Testanspielen OK. Bei Show, Film und Serie kann nach Abschluss der Produktion auch gesendet werden. Produktionsunterbrechung bei Live-Sendungen möchte ich mir nochmal anschauen. Auch Speichern/Laden während eine Produktion läuft, habe ich noch nicht probiert.

Das Aufwerten von Amateuren scheint mir aufgrund der Gagenberechnung im Moment aber noch nicht wirklich attraktiv. Nach der Aufwertung ist die Gage bereits im obersten Preissegment, die Werte von Affinität und Erfahrung sind aber bei 0. Da nimmt man doch lieber einen "billigen" Profi. Die Unterschiede bei den Gagen sind aber ohnehin nochmal ein anderes Thema.

2021-08-20 05:14 UTC, nittka commented
Auch bei einem zweiten kurzen Testspielen konnte ich keine technischen Probleme feststellen. Speichern/Laden während Dreh OK. Produktion durch Live-Übertragung unterbrochen OK. In diesem PR sollte noch die Sortierung angepasst werden. Weitere Auffälligkeiten
* Gagenunterschiede (grundsätzlich) aber insb. Amateur-Aufwertung (sofort unattraktiv teuer - separates Ticket)
* Unterbrechung einer Produktion durch Live-Ausstrahlung OK, aber die laufende Produktion verlängert sich nicht (selbe Fertigstellungszeit wie ohne Live-Ausstrahlung)

2021-08-23 11:53 UTC, GWRon commented
> Name: wirklich nach Name!

Du meinst nach "__Vorname__ Nachname" statt nach "Vorname __Nachname__" ?

2021-08-23 14:09 UTC, nittka commented
> > Name: wirklich nach Name!
> 
> Du meinst nach "**Vorname** Nachname" statt nach "Vorname **Nachname**" ?

Ich meine. Wenn bei der Sortierung "nach Name" gewählt ist, sollte wirklich alle Einträge nach Name sortiert werden und nicht erst alle Amateure nach Name und dann alle anderen nach Name. Am Modus der Namenssortierung wollte ich nichts ändern, da die Spieler das schon so gewohnt sind. Wenn Du allerdings der Meinung bist, dass das gleich mit geändert werden soll, habe ich auch nichts dagegen.

Die anderen Einträge waren analog gemeint. Vor dem Doppelpunkt das gewählte Sortierkriterium (oder mehrere), nach dem Doppelpunkt dann die vorgeschlagene Sortierung.

2021-08-23 14:17 UTC, nittka commented on source/game.screen.supermarket.production.bmx
> +		'sort amateurs "on top"
Hier muss ich mir nochmal probieren, wie sich das im Spiel anfühlt. Nach Gage könnte ja tatsächlich sortiert werden (besonders billiger Profi vs. teurer Amateur). Aber typischerweise würden natürlich die Amateure immer am Anfang stehen. Das fände ich aber auch nicht schlimm, denn bei allen anderen Sortierungen stehen sie ja eben nicht mehr immer vorn...

2021-08-23 14:28 UTC, GWRon commented
- Name: nach Nachname sortieren ("isAmateur" ignorieren)
- Berufserfahrung: Nach Berufserfahrung sortieren, Amateure am Ende und nach "Joberfahrung" sortieren
- Genreerfahrung: Nach Genrerfahrung sortieren, Amateure am Ende und nach "Joberfahrung" sortieren
- Gage: nach Gage sortieren ("isAmateur" ignorieren) 

so? 

Das mit dem Nachnamen ist ... Gewoehnungssache. Aber ich moechte nicht unbedingt
Botterblum, Betty
Droschke, Detlef
....
stehen haben. Auch wenn ich da schlussendlich trotzdem flexibel bin.

2021-08-23 15:24 UTC, nittka commented
Ja, die Auflistung passt. Und wie gesagt, wollte ich Namen gar nicht anders als bisher sortieren.

... Vielleicht sollte die Gagenberechnung doch schon für die kommende Version angepasst werden (wenn auch nicht unbedingt innerhalb dieses PR oder in einer finalen Form). Wenn ich eine Serie mit Amateuren produziere, kostet der Regisseur und Darsteller nach "Aufwertung" (3 Produktionen) schon 200000 und damit mehr als fast alle Profis und das obwohl sie dann weder Erfahrung noch Affinität haben. Das erscheint nicht sinnvoll, insb. wenn ein Profi (der anfänglich im unteren Gagenbereich liegt) nach 3 Produktionen weiterhin so viel wie am Anfang verlangt.

2021-08-24 08:55 UTC, merged