Repo-Cleanup
TVTower/TVTower pull request #461
Opened 2021-11-27 11:36 UTC by nittka

Löschen veralteter Dateien, Verschieben von Dokumentation ins entsprechende Repo, TODOs ins Wiki (vorbereitet). Anpassung der Readme (insb. zu prüfen). Zunächst als Draft.

Closes #457

2021-11-27 12:53 UTC, nittka commented
Die TODOs habe ich ins Wiki übernommen und etwas umstrukturiert. Gern schon mal drüberschauen.

2021-11-28 12:58 UTC, nittka commented
Der Compilation-Guide ist noch nicht in der Dokumentation aber der Branch ist vorbereitet und ein Ticket aufgemacht. Das erste größere Aufräumen wäre von mir aus damit fertig.

2021-12-01 09:48 UTC, GWRon requested changes
Gibt es ein PR fuer das "wiederhinzufuegen" der geloeschten Changelog-Generator (an geeigneterer Stelle) usw?

2021-12-01 09:48 UTC, GWRon commented on README.md
> +- Homepage (+Downloads Linux/Mac/Windows): http://www.tvtower.org
sollten alle httpS sein.

2021-12-01 09:48 UTC, GWRon commented on README.md
> +- Windows (2): TVTowerdownload/TVTower_Win32_DirectX9.bat (force DX7 if misconfigured before)
force DX__9__

2021-12-01 09:48 UTC, GWRon commented on README.md
> +Users of ArchLinux (or Manjaro Linux) in 64 bit might have problems running TVTower (32 bit). If you run these distros in a VM or with an Intel GPU the graphics context is bugged and leads to an segf
Sollte weg koennen - da wir nur noch NG-builds anbieten

2021-12-01 13:43 UTC, nittka commented
Die Changelog-Frage habe ich nicht ganz verstanden. Sollen die Generatoren erhalten bleiben oder wird ohnehin nur das automatisierte Changelog beim GitHub-Tagging verwendet.
Spielt die SVN-Changelog-Datei noch eine Rolle (nach dem Git-Import)?

Vorschlag wäre, ausschließlich die git2log.sh ins Dokumentationsrepo zu schieben (oder nach tools).

2021-12-01 13:54 UTC, GWRon commented
Naja, es ging mir um das Formatiertool fuer changelogs ... die Skripte koennen ja "ausserhalb" aufgehoben werden. 

Die changelog im "release"-Beitrag wird derzeitig ja haendisch durchgecheckt / Unwichtiges gestrichen, manchmal Teile der Beschreibungg in die Zeile 1 uebernommen und der rest geloescht ... sowas halt.

2021-12-01 14:08 UTC, nittka commented
Ich habe mal git2log.sh nach tools verschoben anstatt es zu löschen (in der Annahme, dass das die noch verwendete Datei ist).

2021-12-01 15:01 UTC, nittka commented
Oh. Da hatte ich nicht genau genug nachgeschaut. Ich dachte, changelog.sh bezieht sich auch noch auf svn. Ich schiebe die auch nach tools und squashe alles.

2021-12-01 15:06 UTC, nittka commented
Nun aber.

2021-12-01 15:21 UTC, GWRon commented
Japp, denke so passts.

2021-12-01 15:22 UTC, merged