Fix: [Stationmap] Cancelling contracts and market calculation
TVTower/TVTower pull request #627
Opened 2022-05-27 11:55 UTC by GWRon

2022-05-27 11:56 UTC, GWRon commented
Wenn du mit dem Kabelnetz-Patch einverstanden bist, wuerde ich das bei den Satelliten auch so umsetzen.

2022-05-27 16:15 UTC, nittka requested changes
Erstes Testpiel sieht für die Kabelverträge gut aus. Neben den kleinen Anpassungen also gern auf Satellit übertragen.
Das Beenden der Verträge  beim "Absturz" habe ich noch nicht getestet.

2022-05-27 16:15 UTC, nittka commented on source/game.stationmap.bmx
> +			'count how much of the "mentioned" channels have at least
how many

2022-05-27 16:15 UTC, nittka commented on source/game.stationmap.bmx
> +if index = -1
prints entfernen?

2022-05-31 19:43 UTC, GWRon commented
Satelliten-Berechnung sollte an den entsprechenden Stellen nun gleich wie bei Kabelnetzen ablaufen.

Auch habe "populationShareRatio" entfernt - im Endeffekt ist es ja nur eine Angabe, wie sich die Zahl bezogen auf die Gesamtbevoelkerung verhaelt - laesst sich ja auch so "ausrechnen".


Man koennte nun die Satelliten-"GetReach()"-Funktion noch so umbauen, dass sie wie bei den Kabelnetzen "Rohzahlen" ausgibt (population) und erst auf Wunsch die "SatellitePopulationShareRatio" mit reinkommt.

2022-06-01 06:28 UTC, nittka commented
![viewers](https://user-images.githubusercontent.com/2562651/171337650-e0f39804-38eb-4edc-8c29-809b90d0bc8c.png)

Bei einem gespeicherten Testspiel (ausgehend von einem meiner Branches) sind die Zahlen plausibel aber nicht übereinstimmend. Bevölkerung im Quotenbildschirm und Zuschauer im Sendegebiet weichen leicht ab (allerdings auch, wenn die Spieler nur Antennen und keine Verträge haben). Das betrifft allerdings nicht alle Spielstände, die bei mir rumliegen. Bei anderen passen die Zahlen zusammen. Ein komplett neues Spiel habe ich gerade gestartet. 

Für meine Statistiken habe ich Bau/Aktivierungszeit so gesetzt, dass die neuen Zuschauer immer erst 0 Uhr am nächsten Tag dazukommen. Mir scheint, dass die Marktberechnung nicht berücksichtigt, ob die Antennen/Verträge schon aktiv sind, denn in dem Zeitraum vor der Freischaltung weichen die Zahlen (Bevölkerung Quotenbildschirm und Sendegebiet im Tooltip) voneinander ab. Das ist für den aktuellen Masterstand nicht so problematisch, da die Freischaltung fast unmittelbar erfolgt. Wenn man aber die Bauzeiten hochsetzt, macht es schon einen Unterschied.

(Nicht alle meiner Spielstände konnte ich laden. Zum Teil gab es unmittelbar bei/nach dem Laden Exceptions wegen Illegaler AIEvents)

2022-06-01 06:33 UTC, nittka requested changes
(Die Abweichungen im ersten beschriebenen Fall können auch auf die Bauzeit zurückzuführen sein; gespeichert wird der Spielstand immer kurz vor Mitternacht, so dass die gekauften Antennen da noch nicht aktiv sind). Wie gesagt, betrifft dieses Problem alle Sendetypen und hat nichts mit dem eigentlichen Marktberechnungsproblem für Kabel und Satelliten zu tun. Wenn es sich leicht umsetzen lässt, sollte dieses Problem aber gleich mit behoben werden. Ansonsten OK.

2022-06-01 06:35 UTC, GWRon commented
Das mit den AiEvents hatte ich ja schon mal erwaehnt ..bzw war das was, was du als selbstklaerend angesehen hast.


Die Zuschauerzahlen schaue ich mir gern nochmal an. Hab nur rein die Maerkte beobachtet.

2022-06-06 12:38 UTC, nittka commented
Ich habe die Änderungen rebased auf den Master nochmal ausprobiert. Es muss eine Änderung in meinem Branch gewesen sein, die die Differenzen verursacht hat. Zumindest konnte ich das Problem jetzt nicht noch einmal nachstellen.

Ich lasse die Thematik trotzdem mal auf meiner Beobachtungsliste. Für die Spielstärkelevel sind ja auch die "Bauzeiten" für die unterschiedlichen Varianten anpassbar. Da kann ich die Zahlen nochmal prüfen. Also OK von mir für diesen PR.

2022-06-06 12:39 UTC, nittka approved these changes

2022-06-06 12:46 UTC, nittka commented
Nachtrag: Wenn ich DEV_STATION_CONSTRUCTION_TIME auf 1 setze, passen die Zahlen zwar für Antenne und Kabel zusammen, beim Satelliten wird der Markt allerdings zu früh hochgesetzt.

2022-06-06 20:56 UTC, GWRon commented
Du meinst, noch vor "Uplink-Aktivierung" gehen die Zuschauerzahlen hoch?

Umschreibe mal bitte das gefundene Problem mit anderen Worten - oder einem einfachen Schritt-fuer-Schritt-Beispiel zum nachvollziehen.

2022-06-07 03:47 UTC, nittka commented
* DEV_STATION_CONSTRUCTION_TIME in der DEV.xml auf 1 statt 0 setzen
* neues Spiel starten
* Geld und Image anpassen und Sat-Vertrag abschließen
* im Quotenbildschirm ist die Bevölkerung höher, bevor der Vertrag aktiv ist

2022-06-07 06:29 UTC, GWRon commented
```Blitzmax
	Method GetConstructionTime:Int()
		If GameRules.stationConstructionTime = 0 Then Return 0

		'only need to resume...
		If IsShutDown()
			Return 1 * GameRules.stationConstructionTime
		EndIf

		Local r:Int = GetReach()
		If r < 500000
			Return 1 * GameRules.stationConstructionTime
		ElseIf r < 1000000
			Return 2 * GameRules.stationConstructionTime
		ElseIf r < 2500000
			Return 3 * GameRules.stationConstructionTime
		ElseIf r < 5000000
			Return 4 * GameRules.stationConstructionTime
		Else
			Return 5 * GameRules.stationConstructionTime
		EndIf
	End Method
```

Wenn wir `DEV_STATION_CONSTRUCTION_TIME` auf 1 setzen und einen Satelliten auswaehlen, hat der mehr als 500.000 Zuschauer und die Zeit steigt an.
Soweit, so gut?

An dieser Stelle ist der "DEV"-Kommentar leicht irrefuehrend:
`			<!-- (base) construction time of a new bought station
			     time in hours
			     Default: 0 (ready on next broadcast)

				<DEV_STATION_CONSTRUCTION_TIME value="0" />
			-->
`
Man koennte vermuten, dass die (wenn auch "Basis"-)Bauzeit nicht abhaengig von der Reichweite gesetzt wird. Ich denke wir sollten ueberlegen, den Wert nur bei "-1" zu multiplizieren, und bei den anderen den Wert Fix anzusetzen. Oder einen zweiten DEV-Wert einfuehren (fix construction time...) ?

2022-06-07 08:38 UTC, nittka commented
Im Zuge der Schwierigkeitslevel-Anpassungen wird es hier ohnehin noch Anpassungen geben (bzw. gibt es schon im entsprechenden Branch). 

Resultieren die unterschiedlichen Zuschauerzahlen aus dieser Multiplikation? Ich hätte ja angenommen, dass die final berechnete Aktivierungszeit (d.h. nach Ende der "Bauzeit") sowohl für Markt als auch für Reichweite (für Antenne, Kabel und Satellit gleichermaßen) ausschlaggebend ist.

2022-06-07 11:10 UTC, GWRon commented
Nein das Problem ist eine andere Stelle:

Antennen nutzen "antennaShareGrid", und bei Aenderungen wird das "invalid" gesetzt:
```
	'as soon as a station gets active (again), the sharemap has to get
	'regenerated (for a correct audience calculation)
	Function onSetStationActiveState:Int(triggerEvent:TEventBase)
```
Bis dahin werden "Caches" herangezogen (aka "Keine Aenderung").

Bei Satelliten ist das nun aber anders: da gibt es keinen Cache und es wird einfach "getReach()" benutzt, ohne zu schauen, ob die Uplinks bereit sind oder nicht. (`station.CanBroadcast()` sollte da wohl genutzt werden)

2022-06-07 13:07 UTC, nittka commented
Wenn Kabel und Satelliten gleich für die Märkte gleich behandelt werden, hätte ich das Problem dann aber bei beiden erwartet. Bei beiden ist ja die Reichweite nicht vom Spieler abhängig.

2022-06-07 14:42 UTC, GWRon commented
Bei Kabelnetzen gibt es auch einen Cache, der hier hilfreich dem Problem entgegenwirkt.

2022-06-07 16:13 UTC, nittka commented
Ich werde die Änderungen auch nochmal testspielen, kann aber nicht versprechen, ob das heute noch was wird. Plausibel sieht die Änderung jedenfalls auf.

Perspektivisch könnte man noch darüber nachdenken, den gesamten Markt mit einem Cache zu versehen. Wenn sich bei einem Spieler was an den Zahlen ändern, sind ja potentiell alle Märkte betroffen. In #511 steht dazu ja schon was.

2022-06-07 17:15 UTC, GWRon commented
Beim Markt ist schon der finale Stand enthalten:
- GameModifiers (mehr Zuschauer durch Regenwetter)
- aktuelle Aufteilung zw. den Empfangsmoeglichkeiten


Entsprechend muessten die Caches dann invalidiert werden, wenn etwas eines der benutzten Faktoren aendert:
- entsprechende GameModifiers
- einer der Share-Ratio-Werte
- eine der "Stations" aller vier Spieler


Waere moeglich ...weiss nicht wie cpu-Intensiv die Marktberechnung ist.

2022-06-07 17:46 UTC, nittka commented
Wenn das print raus ist, bin ich zufrieden.
Zum Gesamt-Cache: das kann ja unabhängig vom PR nochmal im Ticket besprochen werden.

2022-06-08 06:04 UTC, merged