Fix: [misc] Enable Save-button when typing. Report: Frohnus
TVTower/TVTower pull request #652
Opened 2022-06-23 22:02 UTC by GWRon

2022-06-23 23:12 UTC, GWRon commented
Eventuell sollten die TGUIModalWindow-Teile direkt auf "Enter" und "Escape" geeicht werden - und den Buttons entsprechende Tasten "hinterlegt" werden (die bei Benutzung der Tasten dann das "onclick" losschicken).
Oder die Buttons koennen Tasten zugewiesen bekommen.

Gleichzeitig koennte man ueberlegen, ob man einen der Buttons hervorhebt, wenn er mit "Enter" verlinkt ist.

Wichtig: es gibt mehrere "Enter" (NUMPAD_ENTER und nur ENTER) ... ist also nicht ganz so einfach umzusetzen.

2022-07-01 12:05 UTC, nittka reviewed
Das eigentliche Problem (Aktivierung des Speichernbuttons bei Eingabe) ist behoben. Die Vorauswahl des Dateinamens ist nur ein Gedankenanstoß.
Unklar ist mir, warum bei TAB die Buttonaktivierung nicht wechselt - es sieht so aus, als ob das KeyEvent gar nicht erst an der gewünschen Stelle ankommt.

Wäre es sinnvoll beim Öffnen des Esc-Menüs auch gleich einen Button zu aktivieren (z.B. Speichern oder Fortsetzen; so dass man mit TAB zwischen den Einträgen hin und herspringen könnte.) Shift-Tab würde in dem Fall auch praktisch sein (voriger Buttung vs. nächster Button).

2022-07-01 14:09 UTC, GWRon commented
Zum Leeren des Eingabefelds:
Tippe einen Namen ein.
Druecke escape.
Gehe wieder ins Menu...und siehe da, alte Eingabe noch drin.

2022-07-02 06:29 UTC, GWRon commented on source/Dig/base.gfx.gui.window.modal.bmx
> +					KeyManager.blockKey(KEY_TAB, 250)
Das Problem ist eher ein Bug in eben diesem Eingabemodus - das manuelle Selektieren von "Speichern" in bestimmten Faellen, bei normalen "Ja / Nein"-Elementen funktioniert es.

![Peek 2022-07-02 08-26_2](https://user-images.githubusercontent.com/2625226/176989434-5683c1c2-bb1d-4a8c-9bf5-48133d5c683d.gif)
![Peek 2022-07-02 08-26](https://user-images.githubusercontent.com/2625226/176989436-11a9003d-ebcc-47d5-9498-1b2562567363.gif)

2022-07-02 06:30 UTC, GWRon commented
Derzeit gibt es noch ein Problem mit der Aktivierung von "Speichern" und dem Verlust des Fokus beim Eingeben von Speicherstandsnamen, deren "Erstbestandteile" mit einem bestehenden Spielstandsnamen übereinstimmen ("Test" besteht und man will "Test2" eintippen - nach Eingabe von "Test" verliert die Eingabe den Fokus)

2022-07-02 07:09 UTC, nittka commented
Leeren des Feldes: Es ging mir eher um den Fall, dass man speichert, ein paar Tage weiterspielt und dann wieder unter demselben Namen speichern möchte.

2022-07-02 07:30 UTC, GWRon commented
> Leeren des Feldes: Es ging mir eher um den Fall, dass man speichert, ein paar Tage weiterspielt und dann wieder unter demselben Namen speichern möchte.

Ja - aendere ich noch.
Der von mir anvisierte Fehler war:
- Speicherdialog oeffnen, eintippen, abbrechen ... neu oeffnen
- da war dann noch der alte Wert drin (da das GUI-Element nicht neuerschaffen wurde - im Gegensatz zum mehrmaligen Oeffnen des Escape-Menues)

2022-07-02 07:59 UTC, GWRon commented
- Neues Spiel: Setzt "zuletzt genutzten Speichername zurueck"
- Geladenes Spiel: Setzt Name auf "Speicherstandsname"
- Spiel speichern: Setzt Name auf "Speicherstandsname"
- Speicherndialog oeffnen: "Speicherstandsname" wird voreingestellt
- Ladendialog oeffnen: "Speicherstandsname" wird voreingestellt

2022-07-02 08:00 UTC, GWRon commented on source/game.menu.escapemenu.bmx
> +		savegameName.SetValue("")
Sollte nun so funktionieren

2022-07-03 08:55 UTC, nittka requested changes
Eine Änderung um Speicherndialog halte ich noch für notwendig. Wenn man den Dateinamen löscht, springt der Fokus von OK auf Abbrechen. Das ist OK. Wenn man dann aber wieder einen Namen eingibt und Enter drückt, bleibt der Fokus auf Abbrechen und man muss für das eigentliche Speichern nochmal TAB drücken.

Es wäre meiner Ansicht nach eigentlich intuitiver, wenn der Buttonfokus erst beim Drücken von Enter überhaupt gesetzt wird. Ansonsten wirkt es so, als würde Enter schon die Speichernaktion abschließen. In diesem Fall kann man den Fokus bei Enter anhand des Feldinhalts (leer/nicht leer) setzen.
Alternativ sollte der Fokus bei nichtleerem Feld sofort wieder von Abbrechen auf Speichern wechseln.

2022-07-03 13:30 UTC, GWRon commented
Sollte nun umgesetzt sein (beides).

2022-07-03 14:58 UTC, nittka approved these changes

2022-07-03 19:33 UTC, merged