Fix: [Programmeplan] Corrected IsModifiableSlot()
TVTower/TVTower pull request #658
Opened 2022-07-04 22:33 UTC by GWRon

references #653

2022-07-04 22:34 UTC, GWRon commented
Der API-Befehl ist nicht umbenannt (Modifyable versus Modifiable). Koennte man nachholen, weiss aber nicht, wie sehr es deinen KI-Branch dann "erschwert".

2022-07-05 14:18 UTC, nittka commented
Nein, so ist es auch nicht richtig.
IsUsableTimeSlot muss doch nur einmal geprüft werden, oder? Da scheint es ja nur darum zu gehen, ob der Slot in der Vergangenheit liegt oder schon angefangen hat - nur abhängig vom Programmtyp nicht vom eigentlichen Programm.
Zur Lock-Info wage ich keine Aussage.

Für "obj" (GetObject(slotType, day, hour)) müsste doch irgendwo geprüft werden, ob es gerade ausgestrahlt wird - dann kann der Slot nicht anders belegt werden.

Im KI-Spiel sieht es so aus, als ob schon gestartete Ausstrahlungen wieder entfernt werden können (Name wird kurz gelb, dann verschwindet er aus dem Programm)... KI will optimieren und entfernt gerade laufendes Programm.
Als menschlicher Spieler im Programmplan kann ich das nicht (noch keine Sonderfälle getestet - Liveübertragungen in der Zukunft).

2022-07-05 14:19 UTC, nittka requested changes
passt noch nicht

2022-07-06 15:40 UTC, nittka commented
Das KI-Verhalten sieht mit dem aktuellen Branch-Stand besser aus. Fachlich hat sich trotzdem noch was geändert: wenn man tagsüber ein X-rated-Programm (mehr als 1 Block) sendet und dieses während des ersten Blocks beschlagnahmt wird, waren früher die restlichen Blöcke nicht neu planbar und weiterhin gesperrt.
Nun kann man für den zweiten Block ein anderes Programm setzen - hat also im besten Fall nur einen Block verloren.

2022-07-07 21:28 UTC, GWRon commented
Falls die Bloecke "gesperrt" werden sollen, koennen wir das in einem neuen Issue gerne angehen (eventuell den "Lock" optional/gamerules-abhaengig machen)

2022-07-08 04:33 UTC, nittka commented
... dann habe ich das beim Ausprobieren einfach falsch gemacht. Vielleicht hatte bei mir dann der zweite Block schon angefangen und ich habe es nur nicht gemerkt. Ich werde das noch einmal testen.

2022-07-09 06:20 UTC, nittka approved these changes

2022-07-09 06:24 UTC, nittka commented
Mein Fehler. Ich hatte das beim Spiel im Masterstand falsch interpretiert. DIe Logausgaben zum "Nichtplanen wegen Slot schon von laufendem Programm belegt" passen nun.
Tatsächlich kommt der Fehler "Failed to place broadcast" weiterhin (aber viel seltener) vor, aber das liegt offensichtlich an der KI. Sie versucht auch in Minute 4 noch für den folgenden Slot zu planen, ist aber nicht immer schnell genug noch in Minute 4 das neue Programm zu platzieren. Darum kümmere ich mich bei den KI-Verbesserungen.

2022-07-09 06:48 UTC, GWRon commented
Solange die KI realisiert, dass sie es 7:04 nicht geschafft hat, 7:05 noch zu planen, ist ja alles OK.

2022-07-09 08:30 UTC, merged