[Misc] Added ${var} support
TVTower/TVTower pull request #680
Opened 2022-09-16 22:04 UTC by GWRon

Allows "nested" variables like ${MAIN${variant}} which resolves ${variant} first and allows to use this variable for others too. ${MAIN{variant}} + ${CHILD{$variant}} both use the same "variant" then.

2022-09-16 22:05 UTC, GWRon commented
Davon unbetroffen sind die Platzhalter in "locales" - das koennen wir aber gern auch umstellen, falls Du da Bedarf drin siehst

2022-09-17 06:25 UTC, nittka commented
Vom Draufschauen sieht es sehr vielversprechend aus. Ich werde das mal intensiv mit den Kultursendungen testen. Eine Lösung, die ohne Datenbank-/Spielstandkorrektur auskommt, ist cool. Rückmeldung folgt.

2022-09-17 08:14 UTC, nittka commented
Sollte hiermit schon die Ersetzung der alten Variante unterstützt sein? Beim Starten eines neuen Spiels werden nämlich die Drehbuchvariablen der Bestandsdaten gar nicht ersetzt!?

2022-09-17 09:42 UTC, GWRon commented
Theoretisch sollte alles ersetzt werden. Schaue mir das aber dann zuhause nochmal an.

2022-09-17 09:51 UTC, nittka commented
Wie gesagt müssen wohl die beiden auskommentierten Zeilen in database.bmx aktiviert werden, damit beide Variablenvarianen unterstützt werden. Allerdings machen die spielinternen Variablen scheinbar doch noch ein Problem. Bei den Börsennachrichten wird der Titel nicht korrekt aufgeklöst.

Altspielstände habe ich noch nicht getestet.

Für die Verwendung des neuen Features aktualisiere ich mal den Branch zu den Kulturdrehbüchern (siehe insb. "X der Welt").

2022-09-17 10:05 UTC, nittka requested changes
Die Nachrichtentitel (Börsennachrichten/Frauenbärte Jahr X) werden noch nicht korrekt umgesetzt.
(Und aus irgendeinem Grund verschwinden die Börsennachrichten irgendwann wieder komplett...)

2022-09-17 15:35 UTC, nittka commented on source/common.misc.templatevariables.bmx
> +					value = value.replace("${"+placeHolder+"}", replacement)
An dieser Stelle müssen beide Variablenvarianten behandelt werden.

2022-09-18 22:26 UTC, GWRon commented on source/common.misc.templatevariables.bmx
> +					value = value.replace("${"+placeHolder+"}", replacement)
OK

2022-09-18 22:28 UTC, GWRon commented on source/game.database.bmx
> +			'newsEventTemplate.templateVariables.AddVariable("%"+varName+"%", varString)
Das verstehe ich nicht ganz?

Extrahierte Variablen werden ja hier der "templateVariables" hinzugefuegt ... sprich sie wurden alle schon ausgelesen, egal ob "%" oder "${".
Welche Codestelle erwartet denn noch die "%"-Variante?

2022-09-19 04:40 UTC, nittka commented on source/game.database.bmx
> +			'newsEventTemplate.templateVariables.AddVariable("%"+varName+"%", varString)
Mit den auskommentierten "%"-Varianten in database.bmx wurden die Ersetzungen nicht durchgeführt. Aufgefallen war das insb. bei den Drehbüchern.
Ich glaube nicht, dass bei den Variablen eine Unterscheidung zwischen "%" und "${" nötig ist. Es sind zwei syntaktische Varianten, wobei die zweite den Vorteil hat, dass öffnende und schließende "Klammer" eindeutig erkennbar sind.

2022-09-19 13:42 UTC, nittka commented on source/game.database.bmx
> +			'newsEventTemplate.templateVariables.AddVariable("%"+varName+"%", varString)
Nochmal ausprobiert. Neues Spiel starten, zum Drehbuchautoren gehn -> die Variablen sind nicht ersetzt. Gleiches bei den Nachrichten.
Vielleicht lässt sich die Prüfung auch zentralisieren, so dass man immer variables.replace(text) aufrufen kann und in dem Aufruf wird dann geprüft, ob text überhaupt einen Marker enthält.

2022-09-19 20:46 UTC, GWRon commented on source/game.database.bmx
> +			'newsEventTemplate.templateVariables.AddVariable("%"+varName+"%", varString)
Das Problem ist der "lookup" in `GetPlaceHolderVariableString()` und in `GetVariableString()`. Diese suchen einfach nach dem uebergebenem Platzhalter inklusive! code-tag.
Wenn dann - wie oben - die "alten" tags nicht mit hinzugefuegt wurden - aber nun nachgefragt, kommt es eben zu diesem Problem.

Eventuell sollte die Liste nur noch "ohne tags" speichern ("var" statt "%var%" bzw "${var}")

2022-09-19 21:59 UTC, GWRon commented
der Einfachheit halber haben die beiden Getter in den "TemplateVariables" nun noch den Fallback fuer "%var%". Das stellt die Funktionalitaet in bestehenden Savegames wieder her.

Die Alternative waere, "interessante" Objekte beim Einladen zu reparieren: Titel, Beschreibungen und "templates".

Weiterhin ein Problem ist Ein text wie der hier:
```
Die tags funktionieren so: \${name} reinschreiben und daraus wird dann "${name}"
```
Der Platzhalterextraktor sieht, dass der erste tag "escaped" ist und findet nur den Zweiten.
Die simple Ersetzung hingegen kuemmert sich nicht um "escapes" und wuerde beide Bereiche ersetzen.
Das kann man umgehen in dem man den String beim Ersetzen wieder "Stueck fuer Stueck" durchgeht und nur valide tags ersetzt ... also wie die Extraktion vorgeht.
Haette aber fuer mich derzeit keine hohe Prioritaet, da wir das "escapen" maximal dazu einsetzen, "%" und "$" (und das nur in Kombination mit der Klammer!) verwenden zu koennen.

2022-09-20 04:34 UTC, nittka commented
(... Das Problem bestand nicht nur in Savegames sondern auch in neu gestarteten Spielen.)
Das Escapen finde ich aktuell auch unproblematisch.

2022-09-20 04:38 UTC, nittka commented on source/common.misc.templatevariables.bmx
> +	Field placeholderVariables:TMap
Ich gehe davon aus, dass alte Spielstände von dieser Feldumbenennung nicht betroffen sind.

2022-09-20 05:03 UTC, GWRon commented
Das ist nur Optik, nicht case-sensitive.

Am 20. September 2022 06:38:39 MESZ schrieb Alexander Nittka ***@***.***>:
***@***.*** commented on this pull request.
>
>
>
>
>
>
>
>>  	'random variable for descendants (episodes refering to the same
>
> 	'keyword) instead of returning other random elements ("option1|option2")
>
>-	Field placeHolderVariables:TMap
>
>+	Field placeholderVariables:TMap
>
>
>
>Ich gehe davon aus, dass alte Spielstände von dieser Feldumbenennung nicht betroffen sind.
>
>
>
>-- >
>Reply to this email directly or view it on GitHub:
>
>https://github.com/TVTower/TVTower/pull/680#pullrequestreview-1113130819
>
>You are receiving this because you authored the thread.
>
>
>
>Message ID: ***@***.***>

2022-09-20 15:26 UTC, nittka approved these changes
Sieht gut aus.

Expressions werden bei der Variablenauswertung ja schon ersetzt. Zumindest funktioniert `${TIME_YEAR}` innerhalb eines Titels.
Wenn ich es richtig verstehe, müsste man nun nur noch eine Expression definieren, die z.B. das x-te Element aus einer Stringliste raussucht und sicherstellen, dass die Expression und ihre Parameter richtig erkannt werden. `${TIME_YEAR=1985}` wird nicht ersetzt - wie wäre denn die richtige Syntax, um eine "Expression-ID" von den Parametern zu trennen, so dass sie erkannt werden?

2022-09-20 21:52 UTC, GWRon commented
Ich verstehe den Teil mit der "Expression-ID" nicht.
Was genau soll unterstuetzt werden - und sollte das Teil dieses PR oder per "neuem Issue" angegangen werden?

2022-09-21 04:35 UTC, nittka commented
Von mir aus kann in der Form gemergt werden. Noch bessere Script-Unterstützung in den Variablen kann in einem separaten Ticket erfolgen.

2022-09-22 19:21 UTC, merged