[Misc] Add savegame compression: faster, smaller!
TVTower/TVTower pull request #781
Opened 2022-12-25 08:55 UTC by GWRon

2022-12-25 09:03 UTC, GWRon commented
der PR benoetigt ein aktuelles "archive.mod":
https://github.com/bmx-ng/archive.mod

Ich hatte Brucey vor einigen Tagen mal angefragt, was fuer Moeglichkeiten er sieht, die von "MXML" erstellten XML-Dateien direkt in ein zip-Archiv zu pressen ("on the fly compression" sozusagen).
Er hat mir dann gesagt, dass "archive.mod" eigentlich genau für solche "stream compressions" einsetzbar waere.

Naja ... es fehlte noch die Moeglichkeit einen Datenstrom (TStream) von archive.mod abgreifen zu koennen. Das hat er nun nachgereicht.


OK, was nun? Der PR-Draft ist erstmal nur in der Lage zu speichern (das Laden hab ich mir zeitlich noch nicht angeschaut). Ich habe da nun verschiedene Kompressionsformate ausprobiert. Zip, Gzip, ...
... und bin bei ZStd von Facebook/Meta oder so gelandet. Und hier kommt das erstaunliche: Die Kompression (im von mir gewaehlten Kompressionslevel 3) ist so schnell, dass hier das Speichern sogar _schneller_ geht.
Unkomprimierter Testspeicherstand: 75mb, speichert in 1750ms
Zstd-komprimierter Speicherstand: 75mb -> 3,7mb und gespeichert in 1700ms.

Neues Spiel-Speicherstand: 17mb, speichert in 450ms
komprimiert: 0,9mb, gespeichert in 420ms

Hoehere Kompressionslevel wuerden gar auf 0,7mb fuer ein neues Spiel komprimieren, aber dann braucht es 500ms (beim grossen Testspeicherstand sind es 3,0mb und es benoetigt 2030ms).

Kurz: Durch die Komprimierung spar ich gar Speicherzeit :)

2022-12-25 17:14 UTC, nittka commented
Die höchste Kompressionsrate benötigen wir sicher nicht. Wie sieht es denn bei Level 1 oder 2 aus? Interessant werden dann nochmal die Ladezeiten. Denn 30 ms beim Speichern sparen um dann 2 Sekunden mehr zum Laden zu brauchen, wäre dann schon schade.
Ich hatte schon mal das Compress-Flag bei TPersist gesehen, aber nicht ausprobiert, ob es funktioniert. Die Idee des Speicherstandaufräumens war ja auch, dass man nichts komprimieren muss, was man gar nicht braucht; nicht nur dass der Speicherstand kleiner wird.

2022-12-25 17:59 UTC, GWRon commented
Level 1 und 2 machens nicht aus.

Zstd soll wohl sehr schnell laden. Evtl laedt es gar schneller als eine unkomprimierte xml.  Da ja weniger Daten zu lesen sind.

Ladezeiten koennen meiner Meinung nach auch hoeher ausfallen. Man speichert ja eher (autosave...) als das man einlaedt. Bzw unterbricht das Einladen den Spielfluss nicht.

2022-12-26 14:06 UTC, GWRon commented
Ich kann nun auch von komprimierten Dateien einladen. Warum auch immer: das einfache Laden aus einer 1MB-Datei in "2048 Bytes"-Schritten dauert hier irgendwie 26 Sekunden. Denke da ist noch irgendwo ein Fehler drin.

Generell ist das neue Namenshandling (Autosave usw) nicht ganz so vorbereitet auf die neue Dateiendung - denke da sollten wir am Ende in einem weiteren Commit mal alles "schoen" machen ;)

2022-12-26 14:35 UTC, GWRon commented
Das Problem mit den 26 Sekunden liegt an der aktuellen "DeserializeFromStream()"-Implementierung:
```
		Local data:String
		Local buf:Byte[2048]
		While Not stream.Eof()
			Local count:Int = stream.Read(buf, 2048)
			data:+ String.FromBytes(buf, count)
		Wend
```
Sie liest in 2kb-Bloecken und fuegt diese immer den aktuellen String an. Der String waechst und waechst ... und am Ende der 17MB XML wird pro Loop ein neuer 17MB-String angelegt (plus 2kb). Ne Menge zu tun fuer den GC :)

Mit nem StringBuilder laedt es nun die Datei in 42ms :)


Komprimiertes "Neues Spiel"-Quicksave laedt in 687ms
Unkomprimiertes "Neues Spiel"-Quicksave laedt in 690ms

Komprimiertes "attempt-reproduce-studio-bug" (3MB) laedt nun in 2900ms hier
Unkomprimiertes "attempt-reproduce-studio-bug" (75MB) laeft in 3340ms.

Bei "HDD" statt "SSD" denke ich sind die Unterschiede nochmal sichtbarer. Allerdings kann es bei langsamen CPUs eventuell laenger de-komprimieren

2022-12-27 16:57 UTC, GWRon commented
Ich wuerde mit diesem Stand in den Reviewprozess gehen ... Hoffe Du bekommst es zum Laufen ;).


Warum die "xml"-Anzeige bei den Savegame-Listen (bzw "zst" wenn man die Komprimierung in GameConfig ausschaelt) ? Wenn wir einen Standard festlegen, sollte die Anzeige nur bei Abweichungen gebraucht werden - sonst lenkt sie nur ab.

2022-12-28 09:42 UTC, nittka commented
Ich muss bei mir die Zeiten nochmal vergleichen, aber das Speichern eines Spielstands vom Tag 40 hat bei mir mit Komprimierung 6 s gedauert. Wenn ich versuche, den Laden-Dialog zu öffenen, kommt es zum Absturz `Read filter not found. Ensure the module has been imported : ` Vielleicht fehlt da eine Systembibliothek?
Wenn ich die zst-Datei lösche, geht es wieder, aber nach dem nächsten Speichern tritt der Fehler wieder auf.

(Ich habe das archive.mod einfach in das mod-Verzeichnis gelegt und danach kompiliert.)

2022-12-28 10:33 UTC, GWRon commented
Mach mal den "quick scan" oder so raus im MaxIDE ... eventuell hat es die archive.mod nicht richtig neukompiliert bzw dann irgend ne andere Datei.

Habe gerade Blitzmax neu aufgesetzt, das fehlende archive.mod frisch runtergeladen (und das script entsprechend angepasst, damit das nicht jedesmal erneut passieren muss :).
Dann den branch hier erstellen lassen...

hat durchkompiliert.
Neues Spiel ... 
F5 ... hat gespeichert
F8 ... hat geladen.

2022-12-28 10:58 UTC, GWRon commented
Irgendwie ist auch "ohne compression" die XML komprimiert ? ... ich schau mir dass nach dem Mittag mal an.

2022-12-28 11:18 UTC, GWRon commented
Eventuell ist die Persistenz von GameConfig ein Problem.

2022-12-28 13:06 UTC, GWRon commented
Ich habe mal den compressionlevel wieder auf 3 gesetzt ... damit sollte es schneller gehen.

Weiterhin habe ich "GetGameSummary" umschreiben muessen - um unabhaengig davon zu sein, ob die XML-Ausgabe formatiert ("Zeilenenden + Einrueckung") ist.

Diese Formatierung habe ich deaktiviert. Wenn Du moechtest, koennen wir die aber gern wieder aktivieren (wenn "unkomprimiert gespeichert"). Die Kompression selbst kommt natuerlich mit Whitespace gut klar.

2022-12-28 14:25 UTC, nittka commented
Für den unkomprimierten Fall wäre mir die Formatierung schon wichtig.

2022-12-28 14:32 UTC, GWRon commented
Du kannst dir mittels externen tools jederzeit XML formatieren lassen..je nach Gusto.

Die Formatierung beizubehalten ist also eher Komfort als Notwendigkeit ;-)

2022-12-28 16:45 UTC, GWRon commented
Hab hier n kleinen Savegame-Converter (GUI) gemacht -- wo hinpacken? "tools" ist ja in der .gitignore denke ich.
Trotzdem als "tools/convert_savegamex.bmx" einbinden?

```BlitzMax
SuperStrict
Framework Brl.StandardIO
Import Archive.ZSTD
Import Archive.RAW
Import Text.mxml
Import Text.xml
Import MaxGUI.Drivers
Import brl.eventQueue


AppTitle = "Savegame converter"
Global windowMain:TGadget = CreateWindow( AppTitle, 100, 100, 700, 280, Null, WINDOW_TITLEBAR|WINDOW_STATUS|WINDOW_CENTER|WINDOW_ACCEPTFILES)
Global filesListBox:TGadget = CreateListBox(0,0,ClientWidth(windowMain),200, windowMain)
Global hintLabel:TGadget = CreateLabel("Drop one or more files on this window",0,240,ClientWidth(windowMain),30, windowMain)
Global convertToZSTButton:TGadget = CreateButton("compress (zst)", 0 * ClientWidth(windowMain)/3, 210, ClientWidth(windowMain)/3,26, windowMain)
Global convertToXMLButton:TGadget = CreateButton("uncompress (xml)", 1 * ClientWidth(windowMain)/3, 210, ClientWidth(windowMain)/3,26, windowMain)
Global resetButton:TGadget = CreateButton("Reset", 2 * ClientWidth(windowMain)/3, 210, ClientWidth(windowMain)/3,26, windowMain)
SetGadgetLayout(hintLabel, EDGE_ALIGNED, EDGE_ALIGNED, EDGE_ALIGNED, EDGE_CENTERED)
SetGadgetLayout(filesListBox, EDGE_ALIGNED, EDGE_ALIGNED, EDGE_CENTERED, EDGE_ALIGNED)
SetGadgetLayout(convertToZSTButton, EDGE_ALIGNED, EDGE_ALIGNED, EDGE_CENTERED, EDGE_ALIGNED)
SetGadgetLayout(convertToXMLButton, EDGE_ALIGNED, EDGE_ALIGNED, EDGE_CENTERED, EDGE_ALIGNED)
SetGadgetLayout(resetButton, EDGE_ALIGNED, EDGE_ALIGNED, EDGE_CENTERED, EDGE_ALIGNED)

Global files:String[]


Repeat
    Select WaitEvent()
        
        Case EVENT_APPTERMINATE, EVENT_WINDOWCLOSE
            End

		Case EVENT_WINDOWACCEPT
			Local temp:String = String(EventExtra())
			If temp
				files :+ [temp]
				AddGadgetItem(filesListBox, temp)
			EndIf
			            
        Case EVENT_GADGETACTION
			If EventSource() = convertToZSTButton
				ConvertFiles("zst")
			ElseIf EventSource() = convertToXMLButton
				ConvertFiles("xml")
			ElseIf EventSource() = resetButton
				files = new String[0]
				For local i:int = 0 until filesListBox.ItemCount()
					filesListBox.RemoveItem(0)
				Next
            EndIf
    EndSelect
Forever




'=====

Function ConvertFiles(targetType:String)
	For Local i:int = 0 until files.length
		ModifyGadgetItem(filesListBox, i, files[i] + " ... processing")
		SetStatusText(windowMain, "Processing: " + files[i])
		PollSystem()

		if targetType = "xml"
			If ExtractExt(files[i]).ToLower() = "xml"
				ModifyGadgetItem(filesListBox, i, files[i] + " ... already uncompressed.")
				SetStatusText(windowMain, "Skipped: " + files[i])
				PollSystem()
			Else
				ConvertZST2XML(files[i], StripExt(files[i]) + ".xml", False)

				ModifyGadgetItem(filesListBox, i, files[i] + " ... uncompressed.")
				SetStatusText(windowMain, "Uncompressed: " + files[i])
				PollSystem()
			EndIf
		ElseIf targetType = "zst"
			If ExtractExt(files[i]).ToLower() = "zst"
				ModifyGadgetItem(filesListBox, i, files[i] + " ... already compressed.")
				SetStatusText(windowMain, "Skipped: " + files[i])
				PollSystem()
			Else
				ConvertXML2ZST(files[i], StripExt(files[i]) + ".zst", False)

				ModifyGadgetItem(filesListBox, i, files[i] + " ... compressed.")
				SetStatusText(windowMain, "Compressed: " + files[i])
				PollSystem()
			EndIf
		EndIf
		'GadgetItemText
	Next

End Function


Function ConvertZST2XML(inputURI:String, outputURI:String, formatXML:Int = True)
	Local ra:TReadArchive = New TReadArchive
	ra.SetFormat(EArchiveFormat.RAW)
	ra.AddFilter(EArchivefilter.ZSTD)

	ra.Open(inputURI)

	Local entry:TArchiveEntry = New TArchiveEntry
	While ra.ReadNextHeader(entry) = ARCHIVE_OK
		Local doc:TxmlDoc = TxmlDoc.readDoc(ra.DataStream())
		doc.saveFile(outputURI, True, formatXML)
		exit
	Wend
	ra.Free() 'do not wait for GC
End Function


Function ConvertXML2ZST(inputURI:String, outputURI:String, formatXML:Int = True)
	Local doc:TxmlDoc = TxmlDoc.parseFile(inputURI)
	If not doc Then Notify "TxmlDoc.readdoc("+inputURI+") failed."
	
	Local saveStream:TSTream = WriteStream(outputURI)
	If not saveStream Then Notify "WriteStream("+outputURI+") failed."

	Local wa:TWriteArchive = New TWriteArchive
	wa.SetFormat(EArchiveFormat.RAW)
	wa.AddFilter(EArchiveFilter.ZSTD)
	wa.SetCompressionLevel(3) 'speed vs size
	wa.Open(outputURI)

	Local entry:TArchiveEntry = New TArchiveEntry
	wa.Header(entry)
	Local xmlArchiveStream:TStream = wa.DataStream()

	doc.saveFile(xmlArchiveStream, False, formatXML)

	wa.FinishEntry()
	entry.Free()
	wa.Close()
	xmlArchiveStream.Close()
End Function
```

2022-12-28 17:57 UTC, nittka commented
Ich bin noch dabei, den Fehler bei mir loszuwerden (hat noch nicht geklappt).
* Einbinden der obigen Datei unter tools - ja; auch wenn das Verzeichnis in gitignore steht, sollte ein explizites Hinzufügen doch funktionieren, oder?
* Die Commits zum DropDown sollten komplett entfernt werden. Meine Vemutung ist, dass bei einem Rebase der erste als "schon vorhanden" erkannt wird und der zweite den eigentlichen Fix dann wieder rückgängig macht, was ja nicht gewollt ist.

2022-12-28 18:32 UTC, nittka commented
Wir hatten doch schon einmal Probleme mit Enum-Arrays. Ich habe nicht mein komplettes Blitzmax aktualisiert sondern nur die Module...
Wenn ich in GetGameSummary den Filter nicht "inline" definiere, sondern explizit
```
Local filters:EArchiveFilter[] = new EArchiveFilter[1]
filters[0] = EArchivefilter.ZSTD
Local ra:TReadArchive = New TReadArchive(EArchiveFormat.RAW, filters)
```
dann kommt es nicht zum Absturz. Die obige Fehlermeldung ist ja schon seltsam, denn eigentlich wird der Filtername (toString) ja mit ausgegeben. Da steht aber nichts.

2022-12-28 18:41 UTC, nittka requested changes
Es sieht so aus, als würden die autosave-Dateien noch nicht ins richtige Verzeichnis geschrieben. Bei mir landen sie im Root-Verzeichnis anstatt in dem Verzeichnis der "Basisdatei" (savegames oder Unterverzeichnis wenn von dort geladen).

2022-12-28 19:16 UTC, GWRon commented
Ich hatte versucht die commit loszuwerden aber laut Dokumentation sollte man bei gepushten Aenderungen den revert-Ansatz waehlen.

2022-12-28 19:18 UTC, GWRon commented
> dann kommt es nicht zum Absturz.

Kannst du die Absturzmeldung mal hinschreiben? Dieser read-Fehler?

Verwunderlich, dass es hier nicht klappt. Es waere schoen ein Standalone-Beispiel zu haben, damit ich es an Brucey weitergeben kann

2022-12-28 19:30 UTC, GWRon commented
Stelle sicher, dass dein bcc neuer als der 2. Dezember ist...

https://github.com/bmx-ng/bcc/commit/a71d5ac32782c7c2b9b52a31781d507006b0b51c

Der Commits sollte eigentlich den Fehler behoben haben

2022-12-28 22:35 UTC, GWRon commented
Brucey meinte, du sollst auch sicherstellen, brl.mod aktualisiert zu haben (wegen der array-Aenderungen)

2022-12-29 07:21 UTC, nittka commented
> Ich hatte versucht die commit loszuwerden aber laut Dokumentation sollte man bei gepushten Aenderungen den revert-Ansatz waehlen.
> 
> Du kannst da gern hier den Branch aufraeumen und ich hole ihn mir dann nach "lokal".

Ich habe die beiden Commits entfernt. Ja, Lehrbuch ist, dass man force-push vermeidet. Historyänderungen machen anderen das Leben schwer. Meine Philosophie ist aber, dass Dir ein Feature-Branch, auf dem ausschließlich Du arbeitest, gehört. Hier ist für mich ein Aufräumen erlaubt und ggf. sogar wünschenswert. Und wie gesagt, hätte ein Rebase-Squash sehr wahrscheinlich dazu geführt, dass eine erwünschte Änderung vom Master rückgängig gemacht worden wäre.

Zum Laufzeitfehler bei mir: nachdem ich die Stelle identifiziert hatte, war mir schon klar, dass mein Stand nicht aktuell genug ist. Ich werde das aufräumen und bin sicher, dass es dann auch ohne Codeanpassungen funktioniert.

Neben dem Schreiben der Autosave-Dateien ins falsche Verzeichnis ist mir noch ein Punkt eingefallen. Wenn man ein Spiel unter demselben Namen wieder speichert, sollte eine ggf. vorhandene Alternativversion (un/compressed) gelöscht werden. Es wäre verwirrend, wenn man sowohl game.xml als auch game.zst auf der Platte liegen hat.

2022-12-29 07:53 UTC, GWRon commented
> Neben dem Schreiben der Autosave-Dateien ins falsche Verzeichnis ist mir noch ein Punkt eingefallen. Wenn man ein Spiel unter demselben Namen wieder speichert, sollte eine ggf. vorhandene Alternativversion (un/compressed) gelöscht werden. 

Ich weiss nicht, ob das automatische Loeschen "so cool" ist. Vielleicht lieber die Dateien in ein Unterverzeichnis verschieben? "old/mysavegame.xml" ?
Will vermeiden, dass jemand ohne explizite Nachfrage einen alten Speicherstand verliert.

Eine etwas kompliziertere Alternative waere es eine Art "ueberschreiben"-Dialog einzufuehren - nur mit 3 Optionen:

"Ein Spielstand mit diesem Namen existiert bereits. Das Speicherformat weicht ab (alt: xml, neu: zst). Was tun?"
[Alten Speicherstand verschieben] [Alten Speicherstand löschen] [Einfach speichern]

2022-12-29 08:08 UTC, nittka commented
Aber was passiert denn aktuell, wenn man einen existierenden Spielstand überschreibt? Er ist hinterher weg und überschrieben. Deshalb hat man ihn doch für das Speichern ausgewählt.

2022-12-29 09:24 UTC, GWRon commented
Derzeit wird aber nicht gefragt, ob man einen Speicherstand ueberschreiben moechte - wenn die Dateiendungen unterschiedlich sind.

Entsprechend wuerde man die Dateiendung gedanklich ausblenden muessen. Unter Linux existieren allerdings Dinge wie "Dateiendungen" nicht - sollte hier kein Problem sein, da wir nur ".xml" und ".zst" zulassen (also "MeinSpeicherstand.vorher" wird immer .xml oder .zst angehangen bekommen).

Ok:
- beim "Check" muessten beide Varianten ueberprueft werden
- existiert bereits eine davon - "overwrite"-Dialog anzeigen
- wird der "overwrite"-Dialog bejaht, muss gecheckt werden, ob eine gleichnamige Dateien mit anderer Endung (also beides, zst UND xml checken) existieren
- wenn ja, diese Datei_en!_ loeschen und dann wie gehabt speichern

2022-12-29 09:42 UTC, nittka commented
... Mein Argument ist ja, dass die Dateiendung irrelevant ist. Wenn ich unter "name" speichern möchte, gibt es hinterher einen Spielstand "name", egal mit welcher Dateiendung (so wie bislang auch). Die Dateiendung ist ja nur ein interner Marker, um zu wissen, welches Format es ist. Führend ist allein der Dateiname.
Den Aufwand mit Dialog würde ich nicht treiben.

2022-12-29 10:14 UTC, GWRon commented
Wir koennten auch den Dateinamen aendern, da die magicbytes gelesen werden...um den Dateityp zu erkennen.
Myname.sav

Aber ja, beim overwrite-Abteil sollten wir die Dateiendung ignorieren. Dazu vorgehen wie ich oben beschrieb.

2022-12-29 13:10 UTC, GWRon commented
Beim Speichern sollte es nun die Dateien vorher loeschen (sofern moeglich). Der Ueberschreiben-Dialog kommt sobald eine zst oder xml-Datei mit dem Namen bereits existiert.

2022-12-29 14:31 UTC, nittka commented
Das Speichern der Autosave-Dateien im richtigen Verzeichnis (gleiches wie Ursprungsdatei) ist noch nicht berücksichtigt, richtig?

2022-12-29 14:36 UTC, GWRon commented
Jetzt schon.

2022-12-29 16:42 UTC, nittka commented
Könntest Du noch den Converter unter tools einchecken (git add -f <name> sollte auch eine Datei in einem ignore-Ordner hinzufügen). Wenn Du dann noch das format-Flag im ConvertZST2XML-Aufruf auf True setzt, passt es für mich.

2022-12-29 16:51 UTC, merged