[Misc] Allow targetgroupcolor referencing
TVTower/TVTower pull request #866
Opened 2023-01-25 15:36 UTC by GWRon

2023-01-25 15:37 UTC, GWRon commented
Der Commit ist gleich ein wenig groesser geworden. Sorry.

Damit istes nun moeglich die Farbe oder das Icon im Text unterzubringen. Allerdings werde ich das wohl noch umschreiben um es huebscher aussehen zu lassen.

![image](https://user-images.githubusercontent.com/2625226/214606491-299dcc62-6bbc-4d9e-9d8d-555c90beed33.png)

2023-01-25 15:39 UTC, GWRon commented
Ich habe eigentlich ueberlegt, das Icon "schick" rechtsseitig anzuordnen - aber nun ist mir aufgefallen, dass es ja mehrere Zielgruppen geben kann und irgendwann der Platz "eng" wird.

Wie damit umgehen?

2023-01-25 15:47 UTC, nittka commented
Das Icon würde ich im Datenblatt fast weglassen. So schrecklich finde ich das Dreieck vor der Zielgruppe im Datenblatt gar nicht. Wichtiger für die Wiedererkennung ist die Markierung der "Kassetten" im Programmplaner. Wenn dort neben (statt?) dem Ausrufezeichen der Farbklecks stünde, hätte man sofort mehr Information.
Für das "Lernen" wäre die entsprechende Markierung bei der Zielgruppenauflistung im Interface auch hilfreich.

2023-01-25 15:53 UTC, GWRon commented
![image](https://user-images.githubusercontent.com/2625226/214610808-13e40f18-b7a9-4141-b110-c35bfe958424.png)

2023-01-25 22:48 UTC, GWRon commented
Bei den Kassetten haben wir ein kleines Problem, sollten mehrere Zielgruppen moeglich sein. Ich denke wir koennten hier nur "die erste" darstellen.

2023-01-25 23:08 UTC, GWRon commented
![image](https://user-images.githubusercontent.com/2625226/214710778-a6313814-b47f-4e75-967c-3661b54795cc.png)

2023-01-26 10:05 UTC, GWRon commented
Es gibt noch ein Problem mit den Spielerfarben - die variieren zwischen "weiteren Spielen".

2023-01-26 17:19 UTC, nittka commented
Ich schau's mir nochmal an. Kannst Du kurz das Spielerfarbenproblem beschreiben? Ich gehe mal nicht davon aus, dass Du meintest, die Farben variieren, wenn man zwischen Spielständen mit unterschiedlich gewürfelten Farben wechselt.
Meintest Du, dass die Reihenfolge der auswählbaren Farben zwischen zwei "Starte neues Spiel" wechselt?

2023-01-26 17:26 UTC, GWRon commented
Siehe oben: Der Fehler ist mit dem Commit "nach der Nachricht" behoben worden.

Problem war: Wenn man im Neues-Spiel-Bildschirm war, zurueck ins Hauptmenue ging und erneut in den Neues-Spiel-Bereich wechselte, so waren die Spielerfarben "neu ausgewuerfelt".

Nun sollte alles wieder "so sein wie vorher"

2023-01-26 17:34 UTC, nittka requested changes

2023-01-26 17:34 UTC, nittka commented on source/main.bmx
> +		print "name: " + name
print noch raus

2023-01-27 15:42 UTC, nittka approved these changes

2023-01-27 16:04 UTC, merged