Minor content corrections
TVTower/TVTower pull request #941
Opened 2023-03-10 04:50 UTC by scr0llbaer9000

Some minor things I found during playtesting.

Some `staff` `function` corrections.

Some adjustments to some `targetgroupattractivity` values.

`Neid-Reiter` for consistency (had long already been used in news items, I had forgotten about the German version; though I don't find that spoof title all too good).

Shortened some too long descriptions (of old items) to fit into the available space.

2023-03-10 05:29 UTC, nittka requested changes
Apart from the one question no objections. Let me know if you want to keep the PR open for potential furter fixes.

2023-03-10 05:29 UTC, nittka commented on res/database/Default/user/jorgaeff.xml
> +				<en>Dyson vs. Klatschkowski: Riots before boxing</en>
before match?

2023-03-11 04:04 UTC, scr0llbaer9000 commented on res/database/Default/user/jorgaeff.xml
> +				<en>Dyson vs. Klatschkowski: Riots before boxing</en>
fine by me.

2023-03-11 04:06 UTC, scr0llbaer9000 commented
Wasn't there a release planned soon?

We can keep this open for things I come across until then. No big additions.

Maybe country `MEX` has to be added now though.

2023-03-11 06:12 UTC, nittka approved these changes
I will wait still with merging in case you have more fixes before the release.

2023-03-12 07:04 UTC, merged