Fix: [Misc] Change currency sign space to non-breaking
TVTower/TVTower pull request #977
Opened 2023-04-02 20:38 UTC by GWRon

Closes #976

2023-04-03 04:31 UTC, nittka requested changes

2023-04-03 04:31 UTC, nittka commented on source/Dig/base.gfx.bitmapfont.bmx
> +	Const NO_BREAKING_SPACE:String = Chr(8239)
160?

2023-04-03 05:07 UTC, GWRon commented on source/Dig/base.gfx.bitmapfont.bmx
> +	Const NO_BREAKING_SPACE:String = Chr(8239)
Ups. War wohl doch schon zu spaet :)

2023-04-03 07:53 UTC, nittka requested changes

2023-04-03 14:14 UTC, nittka approved these changes

2023-04-16 07:11 UTC, nittka commented
Ping für die offenen PRs.

2023-04-16 07:28 UTC, merged